@DeliveryUrl=http://localhost:8080

@CourierUrl=http://localhost:8081

### Create delivery draft
POST {{DeliveryUrl}}/api/v1/deliveries
Content-Type: application/json

{
  "sender": {
    "zipCode": "01001-000",
    "street": "Rua da Consolação",
    "number": "123",
    "name": "João Silva",
    "phone": "11999998888",
    "complement": "Apto 10"
  },
  "recipient": {
    "zipCode": "01001-000",
    "street": "Rua da Consolação",
    "number": "123",
    "name": "João Silva",
    "phone": "11999998888",
    "complement": "Apto 10"
  },
  "items": [
    {
      "name": "Livro de Java",
      "quantity": 2
    }
  ]
}

### DeliveryId
@DeliveryId=aca81ccd-25f0-4a37-a86b-622c8d7805bb

### Update delivery
PUT {{DeliveryUrl}}/api/v1/deliveries/{{DeliveryId}}
Content-Type: application/json

{
  "sender": {
    "zipCode": "01001-000",
    "street": "Rua da Consolação",
    "number": "123",
    "name": "João Silva",
    "phone": "11999998888",
    "complement": "Apto 10"
  },
  "recipient": {
    "zipCode": "01001-000",
    "street": "Rua da Consolação",
    "number": "123",
    "name": "João Silva",
    "phone": "11999998888",
    "complement": "Apto 10"
  },
  "items": [
    {
      "name": "Livro de Spring",
      "quantity": 2
    }
  ]
}

### List paged deliveries
GET {{DeliveryUrl}}/api/v1/deliveries?size=1&page=0

### Find delivery by ID
GET {{DeliveryUrl}}/api/v1/deliveries/{{DeliveryId}}

### Delivery placement
POST {{DeliveryUrl}}/api/v1/deliveries/{{DeliveryId}}/placement

### Delivery pickups
POST {{DeliveryUrl}}/api/v1/deliveries/{{DeliveryId}}/pickups
Content-Type: application/json

{
  "courierId": "981d0657-deed-4ed3-8440-8a40f4b6bd34"
}

### Delivery completion
POST {{DeliveryUrl}}/api/v1/deliveries/{{DeliveryId}}/completion

### Create courier
POST {{CourierUrl}}/api/v1/couriers
Content-Type: application/json

{
  "name": "Maria Entregadora",
  "phone": "11987654321"
}

### CourierId
@CourierId=68740ddb-8662-4b04-89a3-13a2d83d9988

### Edit courier
PUT {{CourierUrl}}/api/v1/couriers/{{CourierId}}
Content-Type: application/json

{
  "name": "Maria Silva",
  "phone": "11987654321"
}

### List paged couriers
GET {{CourierUrl}}/api/v1/couriers?size=1&page=0

### Find courier by ID
GET {{CourierUrl}}/api/v1/couriers/{{CourierId}}

### Calculate courier payload
POST {{CourierUrl}}/api/v1/couriers/payout-calculation
Content-Type: application/json

{
  "distanceInKm": 5.5
}
